environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      PYTHON: "C:\\Python38-x64"
      PYTHON_ARCH: "64"

    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      PYTHON: "3.6"

    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      PYTHON: "3.7"

    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      PYTHON: "3.8"
      coverage: 1

stack: python %PYTHON%

build: off

install:
  # MS Windows config.
  - cmd: 'SET PATH=%PYTHON%;%PATH%'
  - cmd: 'SET PATH=C:\\Python38-x64\\Scripts;%PATH%'
  - cmd: 'echo %PATH%'

  # Shared config for all platforms.
  - python --version
  - git submodule update --init --recursive
  - pip install -r requirements.txt

test_script:
  # GNU/Linux test.
  - sh: ./test.sh

  # MS Windows test.
  - cmd: python -m pytest

  # Shared test for all platforms.
  - git clone https://github.com/UAVCAN/public_regulated_data_types .dsdl-test --branch beta # TODO drop '--branch beta'
  - python -c "import pydsdl; pydsdl.read_namespace('.dsdl-test/uavcan', [])"

after_test:
  # Publish the coverage. The deps are not listed in the requirements file because they are only useful in the CI.
  - sh: "if ((coverage)); then
             pip install pyyaml coveralls;
             coveralls;
         fi"
