# https://www.appveyor.com/blog/2018/04/25/specialized-build-matrix-configuration-in-appveyor/
# https://www.appveyor.com/docs/job-workflows/
# https://www.appveyor.com/docs/how-to/git-push/
environment:
  matrix:
    - job_group: tests
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      PYTHON: "C:\\Python39-x64"

    - job_group: tests
      APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu2004
      PYTHON: "3.9"
      coverage: 1

    - job_group: tests
      APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu2004
      PYTHON: "3.8"

    - job_group: tests
      APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu2004
      PYTHON: "3.7"

    - job_group: tests
      APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu2004
      PYTHON: "3.6"

    - job_name: deploy
      job_depends_on: tests
      APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu2004
      PYTHON: "3.9"

  GIT_TOKEN:
    secure: +jQhxLpePj6hdDryfET/XpLo7VL9fhDXVHlwLOPp/nRDYe97TJAfd0XCTuPz1qkT
  TWINE_USERNAME: __token__
  TWINE_PASSWORD:
    secure: +ZVhECKV0ESBrvUGXVd9wpt9xhMMHeIXSJalghKMKGCrxqvvg7/yMm9kPO+xH1T310zzMpnDUxknR1Q05mjAX5MU70MiHiWAB2fBjNwrMSTQZP4kCpKtznAIM/iCwVczbNolbB3tsUn4OS3rQjXyz7lUdYnaeM7sqF1IZNj55/spCPsAJUmi5DYj8M+6zkaPdCZEswlH7lARJG1g+l4/tbyiBssuyDdmY0AQxJVXDGBXKeHU8frHrWayEI5holjF+oFwx2b6Fz1zZ7uznrGpDQ==

stack: python %PYTHON%
build: off
skip_tags: true

for:
  # TEST PIPELINE
  - matrix:
      only:
        - job_group: tests
    install:
      # MS Windows config.
      - cmd: 'SET PATH=%PYTHON%;%PATH%'
      - cmd: 'SET PATH=C:\\Python38-x64\\Scripts;%PATH%'
      - cmd: 'echo %PATH%'
      # Shared config for all platforms.
      - python --version
      - git submodule update --init --recursive
      - pip install -r requirements.txt
    test_script:
      # GNU/Linux test.
      - sh: ./test.sh
      # MS Windows test.
      - cmd: python -m pytest
      # Shared test for all platforms.
      - git clone https://github.com/UAVCAN/public_regulated_data_types .dsdl-test
      - python -c "import pydsdl; pydsdl.read_namespace('.dsdl-test/uavcan', [])"
    on_success:
      # Publish the coverage. The deps are not listed in the requirements file because they are only useful in the CI.
      - sh: |
          if ((coverage))
          then
            pip install pyyaml coveralls
            coveralls
          fi
  # DEPLOY PIPELINE
  - matrix:
      only:
        - job_name: deploy
    branches:
      only:
        - master
    deploy_script:
      - sh: echo "https://${GIT_TOKEN}:x-oauth-basic@github.com" > ~/.git-credentials
      - sh: git config --global credential.helper store
      - sh: git config --global user.email "devnull@uavcan.org"
      - sh: git config --global user.name  "Release Automation"
      - sh: ./release.sh
