name: 'PyDSDL application builder'

# Runs pydsdl-test job on push to any branch and pull request to master and
# runs both the pydsdl-test and pydsdl-release jobs on push to master branch
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - master

# Ensures that only one workflow is running at a time
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pydsdl-test:
    name: Test PyDSDL
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]
        python: ['3.6', '3.7', '3.8', '3.9', '3.10', '3.11']
        include:
          - os: windows-2019
            python: '3.10'
          - os: macos-latest
            python: '3.9'
    runs-on: ${{ matrix.os }}
    steps:
      # Checkout pydsdl repository
      - name: Check out pydsdl
        uses: actions/checkout@v3

      # Checkout public_regulated_data_types repository
      - name: Check out public_regulated_data_types
        uses: actions/checkout@v3
        with:
          repository: OpenCyphal/public_regulated_data_types
          path: .dsdl-test

      # Install Python version needed for test
      - name: Install Python3
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      # Log Python version
      - name: Log Python version
        run: python --version

      # Install test dependencies
      - name: Install dependencies
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            sudo apt-get install -y linux-*-extra-$(uname -r) graphviz
          fi
          python -m pip install --upgrade pip setuptools nox typed_ast
        shell: bash

      # Run build and test suite
      - name: Run build and test
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            nox --non-interactive --error-on-missing-interpreters --session test test_eol pristine lint --python ${{ matrix.python }}
            nox --non-interactive --session docs
          elif [ "$RUNNER_OS" == "Windows" ]; then
            nox --forcecolor --non-interactive --error-on-missing-interpreters --session test test_eol pristine lint
          elif [ "$RUNNER_OS" == "macOS" ]; then
            nox --non-interactive --error-on-missing-interpreters --session test test_eol pristine lint --python ${{ matrix.python }}
          else
            echo "${{ runner.os }} not supported"
            exit 1
          fi
          python -c "import pydsdl; pydsdl.read_namespace('.dsdl-test/uavcan', [])"
        shell: bash

  pydsdl-release:
    name: Release PyDSDL
    if: (github.event_name == 'push') && (github.ref == 'refs/heads/master')
    needs: pydsdl-test
    runs-on: ubuntu-latest
    steps:
      # Checkout code from GitHub
      - name: Check out
        uses: actions/checkout@v3

      # Build distribution from source
      - name: Build distribution
        run: |
          python -m pip install --upgrade pip setuptools wheel twine
          python setup.py sdist bdist_wheel

      # Obtain release version number
      - name: Get release version
        run: echo "pydsdl_version=$(python3 -c 'import pydsdl; print(pydsdl.__version__)')" >> $GITHUB_ENV

      # Upload distribution to pypi.org
      - name: Upload distribution
        run: |
          python -m twine upload dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN_PYDSDL }}

      # Tag release
      - name: Push version tag
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ env.pydsdl_version }}
          tag_prefix: ''
